### ISSUE TITLE
Create "unified release" file for UnitsDB

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#117]
Right now we have:

```yaml
schema_version: xxx
dimensions:
...
```

```yaml
schema_version: xxx
units:
...
```

etc. 

However, it is inconvenient for users to use multiple files. For management, yes it is convenient to keep them in separate files, but for the user experience, it is inconvenient.

We should have a way to "package" or "consolidate" a release file that is:

```yaml
schema_version: xxx
dimensions:
...
units:
...
quantities:
...
scales:
...
```

Where all of the content is guaranteed to work with each other.

This should be a new CLI command.
