### ISSUE TITLE
Units NISTu374 and NISTu375 point to missing dimension NISTd92 and NISTd93

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#12]
```yaml
"NISTu374":
  dimension_url: "http://ecsed/UnitsML/dimension/id/NISTd92"
  unit_system:
    type: "SI_derived_non-special"
    name: "SI"
  unit_name:
    - "one"
  unit_symbol:
    ascii: "1"
    html: "1"
    latex: '\ensuremath{\mathrm{1}}'
    unicode: "1"

"NISTu375":
  dimension_url: "http://ecsed/UnitsML/dimension/id/NISTd93"
  unit_system:
    type: "SI_derived_non-special"
    name: "SI"
  unit_name:
    - "one"
  unit_symbol:
    ascii: "1"
    html: "1"
    latex: '\ensuremath{\mathrm{1}}'
    unicode: "1"
```

There is no d92/d93 in the dimensions file.
