### ISSUE TITLE
Two instances of in^3 in units.yaml

### ISSUE THREAD

**Issue by opoudjis** [unitsml/unitsdb#16]
NISTu168 and NISTu209 are both cubic inches, and are differentiated only by quantity, volume vs https://en.wikipedia.org/wiki/Section_modulus. In units.yaml, that means they should be treated as the one unit. I am currently pretend-disambiguating them as `in^3` and `in_sectmod^3`.

**Comment by ronaldtse** [comment]
The current `ascii` key is only meant to be used for presentation -- if we want a unique ascii key, that is an extra key/value to enter.

**Comment by opoudjis** [comment]
Ok, then I will add a mandatory "id" key for unit_symbol throughout

**Comment by ronaldtse** [comment]
Something like this I guess:

```yaml
  unit_symbol:
    - id: "kg_per_sec"
      ascii: "kg*s^-1"
      html: "kg/s"
      latex: \ensuremath{\mathrm{kg/s}}
      unicode: "kg/s"
```
