### ISSUE TITLE
Unit u196 missing but referred to as root unit

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#17]
```yml
NISTu196:
  name: gram-force
  symbol: gf
  si: false
  acceptable: false
  short: gram_force
  root: true
```
