### ISSUE TITLE
Units u376-u379 missing

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#18]
```yaml
NISTu376:
  name: light week
  short: light_week
  root: true

NISTu377:
  name: light hour
  short: light_hour
  root: true

NISTu378:
  name: light minute
  short: light_minute
  root: true

NISTu379:
  name: light second
  short: light_second
  root: true
```
