### ISSUE TITLE
Some units do not have all 4 types of renderings, e.g. has 'ascii' but no 'latex'/'unicode'

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#22]
I've already tried to fill in most of them but there are still dozens of them missing some representation.

We need to ensure all these fields are filled.

e.g. 
```yaml
"NISTu258":
  dimension_url: "#NISTd72"
  short: atomic_unit_of_electric_dipole_moment
  root: true
  unit_system:
    type: "non-SI_not_acceptable"
    name: "non-SI"
  unit_name:
    - "atomic unit of electric dipole moment"
  unit_symbols:
    - ascii: "e*a_0"
      html: <i>ea</i> <sub>0</sub>
  root_units:
    enumerated_root_units:
      - unit: "atomic_unit_of_electric_dipole_moment"
        power_denominator: 1
        power_numerator: 1
  quantity_reference:
    - name: "electric dipole moment"
      url: "#NISTq162"

"NISTu259":
  dimension_url: "#NISTd42"
  short: atomic_unit_of_electric_field
  root: true
  unit_system:
    type: "non-SI_not_acceptable"
    name: "non-SI"
  unit_name:
    - "atomic unit of electric field"
  unit_symbols:
    - ascii: "E_h*(e*a_0)"
      html: <i>E</i> <sub>h</sub>/ <i>ea</i> <sub>0</sub>
  root_units:
    enumerated_root_units:
      - unit: "atomic_unit_of_electric_field"
        power_denominator: 1
        power_numerator: 1
  quantity_reference:
    - name: "electric field strength"
      url: "#NISTq68"
```
