### ISSUE TITLE
Some units do not have unit_symbols

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#25]
We need to provide unit_symbols for all units.

e.g. darcy

```yaml
"NISTu157":
  dimension_url: "#NISTd8"
  short: darcy
  root: true
  unit_system:
    type: "non-SI_not_acceptable"
    name: "non-SI"
  unit_name:
    - "darcy"
  root_units:
    enumerated_root_units:
      - unit: "darcy"
        power_denominator: 1
        power_numerator: 1
  quantity_reference:
    - name: "permeability"
      url: "#NISTq72"
    - name: "hydrodynamic permeability"
      url: "#NISTq92"
```
