### ISSUE TITLE
Support on-the-fly generation of (new) composite units encoding

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#27]
A feature of UnitsML is the dynamic encoding of non-UnitsDB units through combining existing units (root or derived units).

We'll have to figure out how to do that.

**Comment by ronaldtse** [comment]
This is an example of "watt per square meter steradian" which is SI-derived and can be (technically) user-defined without needing a UnitsDB entry.

```
"NISTu14.u1e-2/1.u10e-1/1":
  dimension_url: "#NISTd38"
  short:
  root: false
  unit_system:
    type: "SI_derived_non-special"
    name: "SI"
  unit_name:
    - "watt per square meter steradian"
  unit_symbols:
    - ascii: "W*m^-2*sr^-1"
      html: W/(m^2&thinsp;&middot;&thinsp;sr)
      latex: \ensuremath{\mathrm{W/(m^2\cdot sr)}}
      unicode: "W/(m²·sr)"
  root_units:
    enumerated_root_units:
      - unit: "watt"
        power_denominator: 1
        power_numerator: 1
      - unit: "meter"
        power_denominator: 1
        power_numerator: -2
      - unit: "steradian"
        power_denominator: 1
        power_numerator: -1
  quantity_reference:
    - name: "radiance"
      url: "#NISTq89"
```

The key points are:
* user inputs the construction of this composite unit
* generate the symbol representations: `W*m^-2*sr^-1`
* link to a dimension
* link to a quantity
* provide the unit name

Maybe something like this:

```
unitsml(
  composite: watt * meter^-1 * steradian^-1, 
  quantity: radiance
)
```

will already give us what we want?

Questions:
* can the dimension be automatically generated from root units?

"watt per square meter steradian" dimensions:
```
NISTd38:
  mass:
    powerNumerator: 1
    symbol: M
  time:
    powerNumerator: -3
    symbol: T
```

Watt dimensions:
```
NISTd16:
  length:
    powerNumerator: 2
    symbol: L
  mass:
    powerNumerator: 1
    symbol: M
  time:
    powerNumerator: -3
    symbol: T
```

Steradian dimensions:
```
NISTd9:
  dimensionless: true
  plane_angle:
    powerNumerator: 1
    symbol: phi
```

Meter dimensions:
```
NISTd1:
  length:
    powerNumerator: 1
    symbol: L
```

So may be not?
