### ISSUE TITLE
Add units from ISO-IEC 80000 series

### ISSUE THREAD

**Issue by anermina** [unitsml/unitsdb#36]
Several units from ISO-IEC 80000 series are missing in the database:
* Erlang (E)
* Baud (Bd)
* Shannon (Sh)
* Hartley (Hart), 
* Gauss (G) - Gs is supported, but both variants are acceptable, as per IEC 80000-6.

**Comment by ronaldtse** [comment]
Thank you @anermina , can you help make the PR? 

Do we need to add Quantities or only Units?

**Comment by opoudjis** [comment]
Whatever source these have come for, they will need remapping to fit the YAML schema in this repository.

Compare our unitsdb:

Quantity:

````
NISTq158:
  dimension_url: "#NISTd68"
  quantity_type: derived
  quantity_name:
    - relative pressure coefficient
  unit_reference:
    - name: kelvin to the power minus one
      url: "#NISTu5e-1/1"
````

Unit:

````
"NISTu218":
  dimension_url: "#NISTd16"
  short: metric_horsepower
  root: true
  unit_system:
    type: "non-SI_not_acceptable"
    name: "non-SI"
  unit_name:
    - "horsepower, metric"
    - "metric horsepower"
  unit_symbols:
    - id: "hp_metric"
      ascii: "hp"
      html: "hp"
      mathml: "<mi mathvariant='normal'>hp</mi>"
      latex: \ensuremath{\mathrm{hp}}
      unicode: "hp"
  root_units:
    enumerated_root_units:
      - unit: "metric_horsepower"
        power_denominator: 1
        power_numerator: 1
  quantity_reference:
    - name: "power"
      url: "#NISTq20"
````

Whoever does this will also need to supply the unit references for quantities, and they will need to be analysed into base units of the metric system and dimensions whenever possible. Sometimes those analyses can be quite abstract; I remember at least one (angle?) devolving into a ratio.

With the URLs, do NIST need to be consulted to allocate the URIs? Or can we allocate at will?

I'm not volunteering to do this. But someone needs to.
