### ISSUE TITLE
Determine mapping of units to quantities

### ISSUE THREAD

**Issue by opoudjis** [unitsml/unitsdb#4]
Does one unit map to more than one quantity?

Without such one-to-one mappings, quantities will have to be specified separately in input.

**Comment by ronaldtse** [comment]
@opoudjis Most of them are one-to-one, but there are several that can be used with multiple quantities.

e.g.

```yaml
"NISTu319":
  dimension_url: "#NISTd14"
  unit_system:
    type: "non-SI_not_acceptable"
    name: "non-SI"
  unit_name:
    - "centimeter of mercury (0 degC)"
  root_units:
    enumerated_root_units:
      - unit: "0C_cm_Hg"
        power_denominator: 1
        power_numerator: 1
  quantity_reference:
    - name: "pressure"
      url: "#NISTq15"
    - name: "stress"
      url: "#NISTq16"
```
