### ISSUE TITLE
IEC 80000-13: Add Erlang (E), Baud (Bd), Shannon (Sh), Hartley (Hart)

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#40]
The quantities / units of Erlang (E), Baud (Bd), Shannon (Sh), Hartley (Hart) should be added.

**Comment by ronaldtse** [comment]
## Erlang

Quantity:
```yaml
---
- id: t13-1
  num: 13-1
  oldnum: 801
  designations:
    - designation: traffic intensity
      index_as:
        - traffic intensity
  designations_fr:
    - noun: intensité
      gender: f
      adj: de trafic
  symbols:
    - ii(A)
  def: number of simultaneously busy resources in a particular pool of resources
  remarks: See <<iec60050-715,locality:item="715-05-02">>.

- id: t13-2
  num: 13-2
  oldnum: 802
  designations:
    - designation: traffic offered intensity
      index_as:
        - traffic offered intensity
  designations_fr:
    - noun: intensité
      gender: f
      adj: de trafic offert
  symbols:
    - ii(A)_o
  def: |
    traffic intensity (<<t13-1>>) of the traffic that would have been generated by the users of a pool of resources if their use had not been limited by the size of the pool
  remarks: See <<iec60050-715,locality:item="715-05-05">>.

- id: t13-3
  num: 13-3
  oldnum: 803
  designations:
    - designation: traffic carried intensity
      index_as:
        - traffic carried intensity
    - designation: traffic load
      index_as:
        - traffic load
  designations_fr:
    - noun: intensité
      gender: f
      adj: de trafic écoulé
    - noun: charge
      gender: f
      adj: de trafic
  symbols:
    - ii(Y)
  def: traffic intensity (<<t13-1>>) of the traffic served by a particular pool of resources
  remarks: |
    General practice is to estimate the traffic intensity as an average over a specified time interval, e.g. the busy hour.

    See <<iec60050-715,locality:item="715-05-04">>.
```

Units:
```yaml
---
- id: t13-1.a
  num: 13-1.a
  designations:
    - designation: erlang
      index_as:
        - erlang
  symbols: stem:["E"]
  def: stem:[1 " E"] corresponds to the occupancy of one resource
  remarks: The name "erlang" was given to the traffic intensity unit in 1946 by the CCIF, in honour of the Danish mathematician, A. K. Erlang (1878-1929), who was the founder of traffic theory in telephony.

- id: t13-2.a
  num: 13-2.a
  designations:
    - designation: erlang
      index_as:
        - erlang
  symbols: stem:["E"]
  def:
  remarks: See <<t13-1.a>>.

- id: t13-3.a
  num: 13-3.a
  designations:
    - designation: erlang
      index_as:
        - erlang
  symbols: stem:["E"]
  def:
  remarks: See <<t13-1.a>>.
```

## Baud

Quantity:
```yaml
- id: t13-16
  num: 13-16
  oldnum: 816
  designations:
    - designation: modulation rate
      index_as:
        - modulation rate
    - designation: line digit rate
      index_as:
        - line digit rate
  designations_fr:
    - noun: rapidité
      gender: f
      adj: de modulation
    - noun: débit
      gender: m
      adj: en ligne
  symbols:
    - r_"m"
    - u
  def: inverse of the shortest duration of a signal element
  remarks: |
    The term "modulation rate" is used in conventional telegraphy and data transmission. In isochronous digital transmission, the term "line digit rate" is generally used.

    See <<iec60050-704,locality:item="704-17-03">>.
```

Unit:
```yaml
- id: t13-16.a
  num: 13-16.a
  designations:
    - designation: second to the power minus one
      index_as:
        - second to the power minus one
  symbols:
    - s^-1
  def:
  remarks:

- id: t13-16.b
  num: 13-16.b
  designations:
    - designation: baud
      index_as:
        - baud
  symbols: stem:["Bd"]
  def: stem:[1 " Bd" := "unitsml(s^-1)"]
  remarks: |
    Baud is a special name for the second to the power minus one for this quantity.

    The baud may be combined with prefixes, for example kilobaud, symbol stem:["kBd"], megabaud, symbol stem:["MBd"].
```

## Shannon / Hartley

Quantity:
```yaml- id: t13-24
  num: 13-24
  oldnum: 902
  designations:
    - designation: information content
      index_as:
        - information content
  designations_fr:
    - noun: quantité
      gender: f
      adj: d'information
  symbols:
    - I(x)
  def: |
    [stem%unnumbered]
    ++++
    I(x) = "lb" 1/(p(x)) " Sh" = "lg" 1/(p(x))" Hart" = "ln" 1/(p(x)) " nat"
    ++++

    where stem:[p(x)] is the probability of event stem:[x]
  remarks: |
    See <<iso2382-16,locality:item="16.03.02">>.

    See also <<iec60027-3>>.

- id: t13-25
  num: 13-25
  oldnum: 903
  designations:
    - designation: entropy
      index_as:
        - entropy
  designations_fr:
    - noun: entropie
      gender: f
      adj: ' '
  symbols:
    - ii(H)
  def: |
    [stem%unnumbered]
    ++++
    ii(H)(ii(X)) = sum_(i=1)^n p(x_i)ii(I)(x_i)
    ++++

    for the set stem:[ii(X) = {x_1, ..., x_n}]

    where

    stem:[p(x_i)] is the probability and

    stem:[ii(I)(x_i)] is the information content of event stem:[x_i]
  remarks: See <<iso2382-16,locality:item="16.03.03">>.

- id: t13-26
  num: 13-26
  oldnum: 904
  designations:
    - designation: maximum entropy
      index_as:
        - maximum entropy
  designations_fr:
    - noun: entropie
      gender: f
      adj: maximale
  symbols:
    - ii(H)_0
    - (ii(H)_"max")
  def: maximum entropy occurs when stem:[p(x_i) = 1//n] for stem:[i = 1, ..., n]
  remarks: The maximum entropy is sometimes called "decision content" because the value is the same when the base is an integer, for the same number of events. See <<t13-23>>.

- id: t13-28
  num: 13-28
  oldnum: 906
  designations:
    - designation: redundancy
      index_as:
        - redundancy
  designations_fr:
    - noun: redondance
      gender: f
      adj: ' '
  symbols:
    - ii(R)
  def: |
    [stem%unnumbered]
    ++++
    ii(R) = ii(H)_0 - ii(H)
    ++++

    where stem:[ii(H)] is entropy (<<t13-25>>) and stem:[ii(H)_0] is maximum entropy (<<t13-26>>)
  remarks: See <<iso2382-16,locality:item="16.03.05">>.

- id: t13-30
  num: 13-30
  oldnum: 908
  designations:
    - designation: joint information content
      index_as:
        - joint information content
  designations_fr:
    - noun: quantité
      gender: f
      adj: d'information conjointe
  symbols:
    - ii(I)(x, y)
  def: |
    [stem%unnumbered]
    ++++
    ii(I)(x,y) = "lb" 1/(p(x,y)) " Sh" = "lg" 1/(p(x,y)) " Hart" = "ln" 1/(p(x,y)) " nat"
    ++++

    where stem:[p(x, y)] is the joint probability of events stem:[x] and stem:[y]
  remarks:

- id: t13-31
  num: 13-31
  oldnum: 909
  designations:
    - designation: conditional information content
      index_as:
        - conditional information content
  designations_fr:
    - noun: quantité
      gender: f
      adj: d'information conditionnelle
  symbols:
    - ii(I)(x\|y)
  def: |
    information content (<<t13-2>>) of event stem:[x] under the condition that stem:[y] has occurred:

    [stem%unnumbered]
    ++++
    ii(I)(x\|y) = ii(I)(x, y) - ii(I)(y)
    ++++
  remarks: See <<iso2382-16,locality:item="16.04.02">>.

- id: t13-32
  num: 13-32
  oldnum: --
  designations:
    - designation: conditional entropy
      index_as:
        - conditional entropy
    - designation: mean conditional information content
      index_as:
        - mean conditional information content
    - designation: average conditional information content
      index_as:
        - average conditional information content
  designations_fr:
    - noun: entropie
      gender: f
      adj: conditionnelle
  symbols:
    - ii(H)(ii(X)\|ii(Y))
  def: |
    [stem%unnumbered]
    ++++
    ii(H)(ii(X)\|ii(Y)) = sum_(i=1)^n sum_(j=1)^m p(x_i,y_j)ii(I)(x_i\|y_j)
    ++++

    where stem:[p(x_i, y_j)] is the joint probability of events stem:[x_i] and stem:[y_j], and stem:[ii(I)(x_i\|y_j)] is conditional information content (<<t13-31>>)
  remarks: See <<iso2382-16,locality:item="16.04.04">>.

- id: t13-33
  num: 13-33
  oldnum: 910
  designations:
    - designation: equivocation
      index_as:
        - equivocation
  designations_fr:
    - noun: équivoque
      gender: f
      adj: ' '
  symbols:
    - ii(H)(ii(X)\|ii(Y))
  def: conditional entropy (<<t13-32>>) of a set stem:[ii(X)] of emitted characters given the set stem:[ii(Y)] of received characters
  remarks: |
    Equivocation is a quantitative measure of the loss of information due to noise.

    See <<iso2382-16,locality:item="16.04.05">>.

- id: t13-34
  num: 13-34
  oldnum: 911
  designations:
    - designation: irrelevance
      index_as:
        - irrelevance
  designations_fr:
    - noun: altération
      gender: f
      adj: ' '
  symbols:
    - ii(H)(ii(Y)\|ii(X))
  def: |
    conditional entropy (<<t13-32>>) of a set stem:[ii(Y)] of received characters given the set stem:[ii(X)] of emitted characters:

    stem:[ii(H)(ii(Y)\|ii(X)) = ii(H)(ii(X)\|ii(Y)) + ii(H)(ii(Y)) - ii(H)(ii(X))], where
    stem:[ii(H)(ii(X)\|ii(Y))] is equivocation (<<t13-33>>) and stem:[ii(H)] is entropy (<<t13-25>>)
  remarks: |
    Irrelevance is a quantitative measure of the information added to the emitted information due to distortion.

    See <<iso2382-16,locality:item="16.04.06">>.

- id: t13-35
  num: 13-35
  oldnum: 912
  designations:
    - designation: transinformation content
      index_as:
        - transinformation content
  designations_fr:
    - noun: transinformation
      gender: f
      adj: ' '
  symbols:
    - ii(T)(x,y)
  def: |
    [stem%unnumbered]
    ++++
    ii(T)(x,y) = ii(I)(x) + ii(I)(y) - ii(I)(x, y)
    ++++

    where stem:[ii(I)(x)] and stem:[ii(I)(y)] are the information contents (<<t13-24>>) of events stem:[x] and stem:[y], respectively, and stem:[ii(I)(x, y)] is their joint information content (<<t13-30>>)
  remarks: See <<iso2382-16,locality:item="16.04.07">>.

- id: t13-36
  num: 13-36
  oldnum: 913
  designations:
    - designation: mean transinformation content
      index_as:
        - mean transinformation content
  designations_fr:
    - noun: transinformation
      gender: f
      adj: moyenne
  symbols:
    - ii(T)
  def: |
    stem:[ii(T)(x,y) = sum_(i=1)^n sum_(j=1)^m p(x_i,y_j)ii(T)(x_i,y_j)] for the sets

    stem:[ii(X) = {x_1, ..., x_n}], stem:[ii(Y) = {y_1, ..., y_m}],

    where stem:[p(x_i, y_j)] is the joint probability of events stem:[x_i] and stem:[y_j], and stem:[ii(T)(x_i, y_j)] is their transinformation content (<<t13-35>>)
  remarks: See <<iso2382-16,locality:item="16.04.08">>.

- id: t13-37
  num: 13-37
  oldnum: 914
  designations:
    - designation: character mean entropy
      index_as:
        - character mean entropy
  designations_fr:
    - noun: entropie
      gender: f
      adj: moyenne par caractère
  symbols:
    - ii(H)'
  def: |
    [stem%unnumbered]
    ++++
    ii(H)' = "lim"_(m -> oo) (ii(H)_m)/m
    ++++

    where stem:[ii(H)_m] is the entropy (<<t13-3>>) of the set of all sequences of stem:[m] characters
  remarks: See <<iso2382-16,locality:item="16.04.09">>.

- id: t13-38
  num: 13-38
  oldnum: 915
  designations:
    - designation: average information rate
      index_as:
        - average information rate
  designations_fr:
    - noun: débit
      gender: m
      adj: moyen d'entropie
  symbols:
    - ii(H)**
  def: |
    [stem%unnumbered]
    ++++
    ii(H)** = ii(H)' // t(ii(X))
    ++++

    where stem:[ii(H)'] is character mean entropy (<<t13-37>>) and stem:[t(ii(X))] is the mean value of the duration of a character in the set stem:[ii(X)]
  remarks: See <<iso2382-16,locality:item="16.04.10">>.

- id: t13-39
  num: 13-39
  oldnum: 916
  designations:
    - designation: character mean transinformation content
      index_as:
        - character mean transinformation content
  designations_fr:
    - noun: transinformation
      gender: f
      adj: moyenne par caractère
  symbols:
    - ii(T)'
  def: |
    [stem%unnumbered]
    ++++
    ii(T)' = "lim"_(m->oo) (ii(T)_m)/m
    ++++

    where stem:[ii(T)_m] is the mean transinformation content (<<t13-36>>) for all pairs of input and output sequences of stem:[m] characters
  remarks: See <<iso2382-16,locality:item="16.04.11">>.

- id: t13-40
  num: 13-40
  oldnum: 917
  designations:
    - designation: average transinformation rate
      index_as:
        - average transinformation rate
  designations_fr:
    - noun: débit
      gender: m
      adj: moyen de transinformation
  symbols:
    - ii(T)**
  def: |
    [stem%unnumbered]
    ++++
    ii(T)** = (ii(T)')/(sum_(i=1)^n sum_(j=1)^m p(x_i,y_j)t(x_i,y_j))
    ++++

    where stem:[ii(T)'] is character mean transinformation content (<<t13-39>>) and stem:[t(x_i, y_j)] is the mean duration of the pair of characters stem:[(x_i, y_j)] with joint probability stem:[p(x_i, y_j)]
  remarks: See <<iso2382-16,locality:item="16.04.12">>.

- id: t13-41
  num: 13-41
  oldnum: 918
  designations:
    - designation: channel capacity per character
      index_as:
        - channel capacity per character
    - designation: channel capacity
      index_as:
        - channel capacity
  designations_fr:
    - noun: capacité
      gender: f
      adj: de canal par caractère
    - noun: capacité
      gender: f
      adj: de canal
  symbols:
    - ii(C)'
  def: |
    [stem%unnumbered]
    ++++
    ii(C)' = "max" ii(T)'
    ++++

    where stem:[ii(T)'] is character mean transinformation content (<<t13-39>>)
  remarks: See <<iso2382-16,locality:item="16.04.13">>.

- id: t13-42
  num: 13-42
  oldnum: 919
  designations:
    - designation: channel time capacity
      index_as:
        - channel time capacity
    - designation: channel capacity
      index_as:
        - channel capacity
  designations_fr:
    - noun: capacité
      gender: f
      adj: temporelle de canal
    - noun: capacité
      gender: f
      adj: de canal
  symbols:
    - ii(C)**
  def: |
    [stem%unnumbered]
    ++++
    ii(C)** = "max" ii(T)**
    ++++

    where stem:[ii(T)**] is average transinformation rate (<<t13-40>>)
  remarks: See <<iso2382-16,locality:item="16.04.13">>.

```

Unit:
```yaml
- id: t13-24.a
  num: 13-24.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def: value of the quantity when the argument is equal to 2
  remarks: |
    [stem%unnumbered]
    ++++
    1 " Sh" ~~ 0.693" nat" ~~ 0.301" Hart"
    ++++

- id: t13-24.b
  num: 13-24.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def: value of the quantity when the argument is equal to 10
  remarks: |
    [stem%unnumbered]
    ++++
    1 " Hart" ~~ 3.322 " Sh" ~~ 2.303" nat"
    ++++

- id: t13-25.a
  num: 13-25.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks:

- id: t13-25.b
  num: 13-25.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks:

- id: t13-26.a
  num: 13-26.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks:

- id: t13-26.b
  num: 13-26.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks:

- id: t13-28.a
  num: 13-28.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks:

- id: t13-28.b
  num: 13-28.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks:

- id: t13-30.a
  num: 13-30.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks:

- id: t13-30.b
  num: 13-30.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks:

- id: t13-31.a
  num: 13-31.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks:

- id: t13-31.b
  num: 13-31.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks:

- id: t13-32.a
  num: 13-32.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks:

- id: t13-32.b
  num: 13-32.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks:

- id: t13-33.a
  num: 13-33.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks:

- id: t13-33.b
  num: 13-33.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks:

- id: t13-34.a
  num: 13-34.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks:

- id: t13-34.b
  num: 13-34.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks:

- id: t13-35.a
  num: 13-35.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks:

- id: t13-35.b
  num: 13-35.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks:


- id: t13-36.a
  num: 13-36.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks: In practice, the unit "shannon per character" is generally used, and sometimes the units "hartley per character" and "natural unit per character".

- id: t13-36.b
  num: 13-36.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks: In practice, the unit "shannon per character" is generally used, and sometimes the units "hartley per character" and "natural unit per character".

- id: t13-37.a
  num: 13-37.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks:

- id: t13-37.b
  num: 13-37.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks:

- id: t13-38.a
  num: 13-38.a
  designations:
    - designation: shannon per second
      index_as:
        - shannon per second
  symbols: stem:["Sh/s"]
  def:
  remarks:

- id: t13-38.b
  num: 13-38.b
  designations:
    - designation: hartley per second
      index_as:
        - hartley per second
  symbols: stem:["Hart/s"]
  def:
  remarks:

- id: t13-39.a
  num: 13-39.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks: In practice, the unit "shannon per character" is generally used, and sometimes the units "hartley per character" and "natural unit per character".

- id: t13-39.b
  num: 13-39.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks: In practice, the unit "shannon per character" is generally used, and sometimes the units "hartley per character" and "natural unit per character".

- id: t13-40.a
  num: 13-40.a
  designations:
    - designation: shannon per second
      index_as:
        - shannon per second
  symbols: stem:["Sh/s"]
  def:
  remarks:

- id: t13-40.b
  num: 13-40.b
  designations:
    - designation: hartley per second
      index_as:
        - hartley per second
  symbols: stem:["Hart/s"]
  def:
  remarks:

- id: t13-41.a
  num: 13-41.a
  designations:
    - designation: shannon
      index_as:
        - shannon
  symbols: stem:["Sh"]
  def:
  remarks: In practice, the unit "shannon per character" is generally used, and sometimes the units "hartley per character" and "natural unit per character".

- id: t13-41.b
  num: 13-41.b
  designations:
    - designation: hartley
      index_as:
        - hartley
  symbols: stem:["Hart"]
  def:
  remarks: In practice, the unit "shannon per character" is generally used, and sometimes the units "hartley per character" and "natural unit per character".

- id: t13-42.a
  num: 13-42.a
  designations:
    - designation: shannon per second
      index_as:
        - shannon per second
  symbols: stem:["Sh/s"]
  def:
  remarks:

- id: t13-42.b
  num: 13-42.b
  designations:
    - designation: hartley per second
      index_as:
        - hartley per second
  symbols: stem:["Hart/s"]
  def:
  remarks:
```
