### ISSUE TITLE
Add `dBm` (decibels relative to a milliwatt) and `rh` (relative humidity)

### ISSUE THREAD

**Issue by anermina** [unitsml/unitsdb#48]
Is it possible to add `dBm` (decibels relative to a milliwatt) and `rh` (relative humidity) to the database? These are used in JSA-S1022:2024.

![image](https://github.com/user-attachments/assets/83a60086-5fb6-4b0e-a5a4-47abf0c29750)

**Comment by opoudjis** [comment]
I am assigning this to @suleman-uzair, because (as far as I can tell) he is now maintaining this—and more to the point, he is maintaining asciimath2unitsml, which depends on this.

**Comment by opoudjis** [comment]
Note:

* https://en.wikipedia.org/wiki/DBm : dBm is based on metric units, but it is NOT itself an SI unit, and that needs to be reflected in the database, in whatever disclaimer the database allowes: the kWh is another such unit.
* https://en.m.wikipedia.org/wiki/Humidity#Relative_humidity Relative Humidity is also not really an SI unit, it's a conventional ratio. I will note that online usage indicates that the standard notation for it is pretty uniformly _RH_ and not _rh_. For example, https://uvmedico.com/knowledge-base/in-the-product-description-ip66-it-shows-ambient-humidity-5-90-rh.-what-is-the-meaning-in-laymans-terms : 

> When the data sheet for the UV222 Industrial lamp states "Ambient Humidity: 5-90% RH", it means that the lamp works best in this relative humidity range.

We should therefore not make _rh_ the main way of notating this, we should be allowing it as an alternative notation.

**Comment by suleman-uzair** [comment]
> I am assigning this to [@suleman-uzair](https://github.com/suleman-uzair), because (as far as I can tell) he is now maintaining this

@opoudjis, Can you guide me through the process? As I haven’t added/removed anything from the DB yet.
Let me know anything/everything I should know about DB-related changes.

**Comment by opoudjis** [comment]
> > I am assigning this to [@suleman-uzair](https://github.com/suleman-uzair), because (as far as I can tell) he is now maintaining this
> 
> [@opoudjis](https://github.com/opoudjis), Can you guide me through the process? As I haven’t added/removed anything from the DB yet. Let me know anything/everything I should know about DB-related changes.

Suleman, no I cannot. I did this four years ago, I do not remember how I did it, and I am and shall remain completely overwhelmed with Metanorma work. The way for you to do this is to find a comparable non-SI unit in these tables, work out how it has been marked up in these tables, and duplicate its markup for these novel requirements. 

You edit https://github.com/unitsml/unitsdb/blob/main/units.yaml

An exemplar non-SI unit is the decibel itself:

````
NISTu155:
  dimension_url: "#NISTd9"
  short: decibel
  root: false
  prefixed: true
  unit_system:
    type: non-SI_acceptable
    name: non-SI
  unit_name:
  - decibel
  unit_symbols:
  - id: dB
    ascii: dB
    html: dB
    mathml: "<mi mathvariant='normal'>dB</mi>"
    latex: "\\ensuremath{\\mathrm{dB}}"
    unicode: dB
  root_units:
    enumerated_root_units:
    - unit: bel
      power_denominator: 1
      power_numerator: 1
      prefix: d
  quantity_reference:
  - name: logarithmic ratio quantities
    url: "#NISTq90"
````

You're going to add an entry for dBm, and an entry for rh.

I am angry that I have to do the analysis here, when the entire point of delegation is that I do not have the time to, but:

https://en.wikipedia.org/wiki/DBm

> The decibel (dB) is a [dimensionless unit](https://en.wikipedia.org/wiki/Dimensionless_unit), used for quantifying the ratio between two values, such as [signal-to-noise ratio](https://en.wikipedia.org/wiki/Signal-to-noise_ratio). The dBm is also dimensionless,[[1]](https://en.wikipedia.org/wiki/DBm#cite_note-1)[[2]](https://en.wikipedia.org/wiki/DBm#cite_note-2) but since it compares to a fixed reference value, the dBm rating is an absolute one.

We have a bigger issue here with RH. Relative permeability, relative mass density, etc are NOT treated as valid SI units, being ratios: their SI unit is 1. We do NOT have non-SI synonyms for them, e.g. we do not have Specific Gravity (SG) as a unit for https://en.wikipedia.org/wiki/Relative_density. I'm going to introduce one for RH, but frankly, I am not a metrologist either, and this repository should be being maintained by specialists, not random developers.

The update here is as follows (remove comments):

Again, I do not have the time to maintain this, or tell you how to. You will need to work out how I have done this update.

units.yml

````
NISTu402:
  dimension_url: "#NISTd9" /* reference to dimenions.yaml: dimensionless*/
  short: decibel-milliwatts
  root: false
  prefixed: true
  unit_system:
    type: non-SI_acceptable
    name: non-SI
  unit_name:
  - decibel-milliwatts
  unit_symbols:
  - id: dBm
    ascii: dBm
    html: dBm
    mathml: "<mi mathvariant='normal'>dBm</mi>"
    latex: "\\ensuremath{\\mathrm{dBm}}"
    unicode: dBm
  root_units:
    enumerated_root_units:
    - unit: bel
      power_denominator: 1
      power_numerator: 1
      prefix: d
    - unit: watt
      power_denominator: 1
      power_numerator: -1 /* it's db * mW^-1 */
      prefix: m
  quantity_reference:
  - name: logarithmic ratio quantities
    url: "#NISTq90" /* reference to quantities.yaml: it's the ratio of a logarithmic ratio (db) to another quantity, but ratios do only appear once in the quantities yaml */

NISTu61:
  dimension_url: "#NISTd80"
  short: one
  root: false
  unit_system:
    type: SI_derived_non-special
    name: SI
  unit_name:
  - one
  unit_symbols:
  - id: '1'
    ascii: '1'
    html: '1'
    mathml: "<mi mathvariant='normal'>1</mi>"
    latex: "\\ensuremath{\\mathrm{1}}"
    unicode: '1'
  quantity_reference:
  - name: refractive index
    url: "#NISTq93"
  - name: rotation
    url: "#NISTq111"
  - name: relative permeability
    url: "#NISTq94"
  - name: relative mass density
    url: "#NISTq125"
  - name: linear strain
    url: "#NISTq136"
  - name: shear strain
    url: "#NISTq137"
  - name: volume strain
    url: "#NISTq138"
  - name: Poisson number
    url: "#NISTq140"
  - name: dynamic friction factor
    url: "#NISTq147"
  - name: logarithmic decrement
    url: "#NISTq121"
  - name: nil
    url: "#NISTq1002"
  - name: relative humidity /* added */
    url: "#NISTq1003" 


NISTu403:
  dimension_url: "#NISTd80" /* reference to dimenions.yaml: this is a ratio */
  short: relative-humidity
  root: true /* no prefix, basic unit */
  prefixed: true
  unit_system:
    type: non-SI_acceptable
    name: non-SI
  unit_name:
  - relative humidity
  unit_symbols:
  - id: RH
    ascii: RH
    html: RH
    mathml: "<mi mathvariant='normal'>RH</mi>"
    latex: "\\ensuremath{\\mathrm{RH}}"
    unicode: RH
  - id: rh /* second unit symbol is alt */
    ascii: rh
    html: rh
    mathml: "<mi mathvariant='normal'>rh</mi>"
    latex: "\\ensuremath{\\mathrm{rh}}"
    unicode: rh
  root_units:
    enumerated_root_units:
    - unit: bel
      power_denominator: 1
      power_numerator: 1
      prefix: d
    - unit: watt
      power_denominator: 1
      power_numerator: -1 /* it's db * mW^-1 */
      prefix: m
  quantity_reference:
  - name: relative humidity
    url: "#NISTq1003" /* see below */
````

As far as I can tell, there is no cross-referencing needed of non-SI NISTu403 to SI NISTu61: the fact that they both measure NISTq1003 is sufficient to identify them as equivalents.

quantities.yml

````
NISTq90:
  dimension_url: "#NISTd67"
  quantity_type: derived
  quantity_name:
  - logarithmic ratio quantities
  unit_reference:
  - name: neper
    url: "#NISTu153"
  - name: bel
    url: "#NISTu154"
  - name: decibel
    url: "#NISTu155"
  - name: decibel-milliwats
    url: "#NISTu402" /* forward reference */

NISTq1003:
  dimension_url: "#NISTd80"
  quantity_type: derived
  quantity_name:
  - relative humidity /* copy pasted from relative permeability */
  unit_reference:
  - name: one
    url: "#NISTu61"
  - name: relative-humidity 
    url: "#NISTu403"
````

You must work out why I have made these edits. Make the edits, and then confirm that UnitsML containing dbm and rh are processed correctly.
