### ISSUE TITLE
Quantity NISTq8 "area" listed as `quantity_type: base`?

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#58]
There are 7 `quantity_type: base` quantities according to the SI system.

These are:

(NISTq1) Length, (NISTq48) Distance::
The measurement of distance or dimension in one direction.

(NISTq2) Mass::
The measurement of the amount of matter in an object.

(NISTq3) Time/Duration::
The measurement of duration or sequential events.

(NISTq4) Electric current::
The flow of electric charge.

(NISTq5) Thermodynamic temperature::
The measurement of thermal energy.

(NISTq6) Amount of substance::
The number of entities (atoms, molecules, ions, etc.) in a system.

(NISTq7) Luminous intensity::
The measure of the power of light in a given direction.

But why is "area" listed as one? It should be of type `derived`...?

```yaml
NISTq8:
  dimension_url: "#NISTd8"
  quantity_type: base
  quantity_name:
  - area
```
