### ISSUE TITLE
Harmonize cross-reference structures

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#62]
We should have a single way of referencing other UnitsDB entities.

## Quantities

``` yaml
NISTq158:
  dimension_url: "#NISTd68"
```

```yaml
NISTq158:
  # ...
  unit_reference:
    - name: kelvin to the power minus one
      url: "#NISTu5e-1/1"
```

## Units

```yaml
"NISTu1":
  dimension_url: "#NISTd1"
```

```yaml
"NISTu1":
  # ...
  quantity_reference:
    - name: "length"
      url: "#NISTq1"
    - name: "diameter"
      url: "#NISTq100"
```
