### ISSUE TITLE
Using org-neutral identifiers

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#63]
This was a topic discussed with the BIPM some time ago. We should adopt vendor/organization neutral identifiers (and can support aliases) for wider acceptance.

This applies to all types of objects.

**Comment by ronaldtse** [comment]
We will adopt the `short` identifier for unitsml as follows:

```yaml
id: {entity type}:{short name}
type: unitsml
```

e.g.
```yaml
- identifiers:
  - id: u:foot
    type: unitsml
  - id: NISTu78
    type: nist
```
