### ISSUE TITLE
Excessive cross-references causing potential inconsistencies

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#64]
## Quantity

References dimension and unit:

```yaml
NISTq20:
  dimension_url: "#NISTd16"
  quantity_type: derived
  quantity_name:
  - power
  unit_reference:
  - name: horsepower, electric
    url: "#NISTu127"
  - name: watt
    url: "#NISTu14"
```

## Unit

References dimension, unit system and quantity:

```yaml
NISTu185:
  dimension_url: "#NISTd57"
  short: meter_to_the_power_four
  root: false
  unit_system:
    type: non-SI_not_acceptable
    name: non-SI
...
  quantity_reference:
  - name: second axial moment of area
    url: "#NISTq144"
```

## Problem

We need to:
1. Validate whether the referenced items exist
2. Normalize so that relationships are only created one way
3. A unit may belong to multiple unit systems, e.g. the acceptance criteria of BIPM and SP 811 can be different (see #2 ), so a unit can be acceptable in one system but not in another.
