### ISSUE TITLE
YAML structure: `root_units.enumerated_root_units` is an unnecessary layer

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#69]
```yaml
  root_units:
    enumerated_root_units:
    - power_numerator: 1
      unit: imperial_gallon
```

Could just be:

```yaml
  root_units:
  - power_numerator: 1
    unit: imperial_gallon
```
