### ISSUE TITLE
YAML structure: when a unit has no external root-unit, it should just have the `root_units:` empty

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#70]
As title.

```yaml
NISTu171:
  dimension_url: "#NISTd10"
  quantity_reference:
  - name: volume
    url: "#NISTq10"
  root: true
  root_units:
    enumerated_root_units:
    - power_numerator: 1
      unit: imperial_gallon
  short: imperial_gallon
  unit_name:
  - gallon (UK)
  - imperial gallon
  - gallon
```

Can just be:

```yaml
NISTu171:
  dimension_url: "#NISTd10"
  quantity_reference:
  - name: volume
    url: "#NISTq10"
  root: true
  short: imperial_gallon
  unit_name:
  - gallon (UK)
  - imperial gallon
  - gallon
```
